=== timrestart/VoyageurDeSante/src/data/xsd/cabinet.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://www.ujf-grenoble.fr/l3miage/medical"
		   xmlns:med="http://www.ujf-grenoble.fr/l3miage/medical"
		   elementFormDefault="qualified">

	<!-- Racine cabinet -->
	<xs:element name="cabinet" type="med:Cabinet">
		<!-- Contrainte : l'intervenant d'une visite doit exister/travailler au cabinet -->
		<xs:keyref name="intervenantExiste" refer="infirmierUnique">
			<xs:selector xpath="med:patients/med:patient/med:visite"/>
			<xs:field xpath="@intervenant"/>
		</xs:keyref>
	</xs:element>
	

	<!-- Type complexe Cabinet -->
	<xs:complexType name="Cabinet">
		<xs:sequence>
			<xs:element name="nom" type="xs:string"/>
			<xs:element name="adresse" type="med:Adresse"/>
			<xs:element name="infirmiers" type="med:Infirmiers">
				<!-- Contrainte : chaque infirmier du cabinet a un identifiant unique -->
				<xs:key name="infirmierUnique">
					<xs:selector xpath="med:infirmier"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
			<xs:element name="patients" type="med:Patients"/>
		</xs:sequence>
	</xs:complexType>
	

	<!-- Type complexe Adresse -->
	<xs:complexType name="Adresse">
		<xs:sequence>
			<xs:element name="étage" type="xs:int" minOccurs="0" maxOccurs="1"/>
			<xs:element name="numéro" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
			<xs:element name="rue" type="xs:string"/>
			<xs:element name="ville" type="xs:string"/>
			<xs:element name="codePostal" type="xs:nonNegativeInteger"/>
		</xs:sequence>
	</xs:complexType>


	<!-- Type complexe Infirmiers -->
	<xs:complexType name="Infirmiers">
		<xs:sequence>
			<xs:element name="infirmier" type="med:Infirmier" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Type complexe Infirmier -->
	<xs:complexType name="Infirmier">
		<xs:sequence>
			<xs:element name="nom" type="xs:string"/>
			<xs:element name="prénom" type="xs:string"/>
			<xs:element name="photo" type="xs:string"/>		<!-- [!] element photo devrait etre de type Photo -->
		</xs:sequence>
		<xs:attribute name="id" type="med:Id"/>
	</xs:complexType>

	<!-- Type simple Id -->
	<xs:simpleType name="Id">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Type simple Photo -->
	<!-- [!] regex non valide

	<xs:simpleType name="Photo">
		<xs:restriction base="xs:string">
			<xs:pattern value="*\.(png|jpg)"/>
		</xs:restriction>
	</xs:simpleType>

	-->

	<!-- Type complexe Patients -->
	<xs:complexType name="Patients">
		<xs:sequence>
			<xs:element name="patient" type="med:Patient" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Type complexe Patient -->
	<xs:complexType name="Patient">
		<xs:sequence>
			<xs:element name="nom" type="xs:string"/>
			<xs:element name="prénom" type="xs:string"/>
			<xs:element name="sexe" type="med:Sexe"/>
			<xs:element name="naissance" type="xs:date"/>
			<xs:element name="numéro" type="med:NuméroSecu"/>
			<xs:element name="adresse" type="med:Adresse"/>
			<xs:element name="visite" type="med:Visite"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Type simple Sexe -->
	<xs:simpleType name="Sexe">
		<xs:restriction base="xs:string">
			<xs:enumeration value="M"/>
			<xs:enumeration value="F"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Type simple NuméroSecu -->
	<xs:simpleType name="NuméroSecu">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{15}"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Type complexe etendu Visite avec base VisiteBase -->
	<xs:complexType name="Visite">
		<xs:complexContent>
			<xs:extension base="med:VisiteBase">
				<xs:attribute name="intervenant" type="med:Id"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- Type complexe VisiteBase -->
	<xs:complexType name="VisiteBase">
		<xs:sequence>
			<xs:element name="acte" type="med:Acte" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="date" type="xs:date"/>
	</xs:complexType>

	<!-- Type complexe etendu Acte avec pour base xs:string -->
	<xs:complexType name="Acte">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="id" type="med:Id"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== timrestart/VoyageurDeSante/src/data/xml/cabinet.xml
<?xml version="1.0" encoding="UTF-8"?>

<cabinet
	xmlns="http://www.ujf-grenoble.fr/l3miage/medical"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ujf-grenoble.fr/l3miage/medical ../xsd/cabinet.xsd">

	<!-- Nom du cabinet -->
	<nom>Soins à Grenoble</nom>

	<!-- Adresse du cabinet -->
	<adresse>
		<numéro>60</numéro>
		<rue>rue de la Chimie</rue>
		<ville>Grenoble</ville>
		<codePostal>38041</codePostal>
	</adresse>

	<!-- Liste des infirmiers du cabinet -->
	<infirmiers>
		<infirmier id="001">
			<nom>Fréchie</nom>
			<prénom>Sarah</prénom>
			<photo>sarah.png</photo>
		</infirmier>
		<infirmier id="002">
			<nom>Stické</nom>
			<prénom>Sophie</prénom>
			<photo>sophie.jpg</photo>
		</infirmier>
		<infirmier id="003">
			<nom>Ochon</nom>
			<prénom>Paul</prénom>
			<photo>paul.png</photo>
		</infirmier>
	</infirmiers>

	<!-- Liste des patients du cabinet -->
	<patients>
		<!-- Homme, né en août 98 en France, à Marseille (n°55 en bouches du rhône)
		458e naissance -->
		<patient>
			<nom>Alécole</nom>
			<prénom>Yvon</prénom>
			<sexe>M</sexe>
			<naissance>1998-08-22</naissance>
			<numéro>198082205545852</numéro>
			<adresse>
				<étage>6</étage>
				<numéro>50</numéro>
				<rue>avenue Félix Viallet</rue>
				<ville>Grenoble</ville>
				<codePostal>38031</codePostal>
			</adresse>
			<visite date="2015-12-08" intervenant="001">
				<acte id="109"/>
			</visite>
		</patient>

		<!-- Elvire est née le 08 mars 82 en France, à Lyon (n°23 dans le rhône),
		il s'agissait de la 52e naissance dans cette ville -->
		<patient>
			<nom>Orouge</nom>
			<prénom>Elvire</prénom>
			<sexe>F</sexe>
			<naissance>1982-03-08</naissance>
			<numéro>282036902305218</numéro>
			<adresse>
				<rue>Ron-Point de la Croix de Vie</rue>
				<ville>Grenoble</ville>
				<codePostal>38700</codePostal>
			</adresse>
			<visite date="2015-12-08" intervenant="002">
				<acte id="300"/>
			</visite>
		</patient>

		<!-- Oscare est née le 25 mars 75 en France, à Chambéry (n°65 dans la Savoie)
		Il s'agissait de la 692e naissance.-->
		<patient>
			<nom>Pien</nom>
			<prénom>Oscare</prénom>
			<sexe>F</sexe>
			<naissance>1975-03-25</naissance>
			<numéro>275037306569202</numéro>
			<adresse>
				<rue>rue Casimir Brenier</rue>
				<ville>Grenoble</ville>
				<codePostal>38000</codePostal>
			</adresse>
			<visite date="2015-12-08" intervenant="001">
				<acte id="101"/>
				<acte id="104"/>
			</visite>
		</patient>

		<!-- Oscare est née le 25 mars 75 en France, à Chambéry (n°65 dans la Savoie)
		Il s'agissait de la 692e naissance.-->
		<patient>
			<nom>Pien</nom>
			<prénom>Oscare</prénom>
			<sexe>F</sexe>
			<naissance>1975-03-25</naissance>
			<numéro>275037306569202</numéro>
			<adresse>
				<rue>rue Casimir Brenier</rue>
				<ville>Grenoble</ville>
				<codePostal>38000</codePostal>
			</adresse>
			<visite date="2015-12-11" intervenant="001">
				<acte id="109"/>
				<acte id="102"/>
			</visite>
		</patient>

		<!-- Xavier est un petit garçon de 4 ans, né le 02 août 2011 en France,
		à Bordeaux (n°63 dans la Gironde). Il s'agi de la 35e naissance. -->
		<patient>
			<nom>Kapoëtla</nom>
			<prénom>Xavier</prénom>
			<sexe>M</sexe>
			<naissance>2011-08-02</naissance>
			<numéro>111083306303521</numéro>
			<adresse>
				<numéro>25</numéro>
				<rue>rue des Martyrs</rue>
				<ville>Grenoble</ville>
				<codePostal>38042</codePostal>
			</adresse>
			<visite date="2015-12-08" intervenant="003">
				<acte id="111"/>
			</visite>
		</patient>

	</patients>

</cabinet>
